config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'submissions#index'
  resources :submissions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
	validates_uniqueness_of :name
	validates_presence_of :name, :contribution
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
	def index
		@submission = Submission.new
		@submissions = Submission.all
	end

	def create
		@submission = Submission.new(submission_params)
		if @submission.save
			flash[:warning] = "Thank you for your lit contribution 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
		else
			flash[:danger] = @submission.errors.full_messages
		end
		redirect_to
	end

	def edit
		@submission = Submission.find(params[:id])
	end

	def update
		update = Submission.find(params[:id]).update(submission_params)
		if update 
			flash[:warning] = 'Lit Update! Lit. 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥'
			redirect_to root_path
		else 
			flash[:danger] = 'Nah fam, you need to contribute 😒🖕'
			redirect_to edit_submission_path(params[:id])
		end
	end

	def destroy
		Submission.find(params[:id]).destroy
		redirect_to root_path
	end

	private

		def submission_params
			params.require(:submission).permit(:name, :contribution)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header text-center">
        <h1>Famsgiving: What you bringin!?</h1>
      </div>
    </div>
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6">
      <% if @submissions.empty? %>
      <p class="text-center">No on is signed up yet! 😰</p>
      <%else%>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead >
            <tr>
              <th>Name</th>
              <th>Contribution</th>
            </tr>
          </thead>
          <tbody>
            <% @submissions.each do |submission| %>
            <tr>
              <td><%= submission.name %></td>
              <td><%= submission.contribution %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      I'm gonna bring...
      </button>
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">What you bringin?!</h4>
            </div>
            <div class="modal-body">
              <%= form_for @submission, url: home_index_path(@submission) do |f| %>
                <div class="form-group">
                  <%= f.label :name, class: "control-label" %>:
                  <%= f.text_field :name, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :contribution %>:
                  <%= f.text_area :contribution, rows:5, class:"form-control" %>
                </div>
                      
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit 'Submit', class:"btn btn-primary" %>
              <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Famsgiving</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<%= render 'shared/navbar' %>
		<%= render 'shared/flash' %>
		<%= yield %>
	</body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
	<% flash.each do |key, value| %>
	<div class="alert alert-dismissible alert-<%= key %>">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= value %>
	</div>
	<%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
  		<%= link_to "Famsgiving", root_path, class: "navbar-brand"%>
    </div>
      </div><!-- /.container-fluid -->
    </nav>

app/views/submissions/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1>
				Edit Submission
				<%= link_to submission_path(@submission), method: :delete, class: "pull-right", data: {confirm: "Are you sure you want to delete this?"} do %>
				<i class="fa fa-trash-o" aria-hidden="true"></i>
				<%end%>
				</h1>
			</div>
		</div>
		<div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6">
			<%= form_for @submission, method: :patch do |f| %>
			<div class="form-group">
				<%= f.label :name, class: "control-label" %>:
				<%= f.text_field :name, class: "form-control", disabled: "" %>
			</div>
			<div class="form-group">
				<%= f.label :contribution %>:
				<%= f.text_area :contribution, rows:5, class:"form-control" %>
			</div>
			<%= f.submit 'Submit', class:"btn btn-primary" %>
			<%end%>
		</div>
	</div>
</div>

app/views/submissions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header text-center">
        <h1>Famsgiving: What you bringin!?</h1>
      </div>
    </div>
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6">
      <% if @submissions.empty? %>
      <p class="text-center">No one is bringing anything yet! 😰</p>
      <%else%>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead >
            <tr>
              <th>Name</th>
              <th>Contribution</th>
            </tr>
          </thead>
          <tbody>
            <% @submissions.each do |submission| %>
            <tr>
              <td><%= submission.name %></td>
              <td><%= submission.contribution %>
                <span class="pull-right">
                  <%= link_to edit_submission_path(submission) do %>
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                </span>
              </td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      I'm gonna bring...
      </button>
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">What you bringin?!</h4>
            </div>
            <div class="modal-body">
              <%= form_for @submission do |f| %>
                <div class="form-group">
                  <%= f.label :name, class: "control-label" %>:
                  <%= f.text_field :name, class: "form-control", placeholder: "William Huang" %>
                </div>
                <div class="form-group">
                  <%= f.label :contribution %>:
                  <%= f.text_area :contribution, rows:5, class:"form-control", placeholder: "Mashed potatoes, A bottle of wine, napkins" %>
                </div>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit 'Submit', class:"btn btn-primary" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>